{% set version = "1.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rpref
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rPref_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rPref/rPref_{{ version }}.tar.gz
  sha256: 5c38750829772bf55f8b8e2231618a88e9438bd884274f398a754b5758258bfa

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=1.0.0
    - r-rcppparallel >=4.3.6
    - r-dplyr >=0.8.0
    - r-igraph >=1.0.1
    - r-lazyeval >=0.2.1
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=1.0.0
    - r-rcppparallel >=4.3.6
    - r-dplyr >=0.8.0
    - r-igraph >=1.0.1
    - r-lazyeval >=0.2.1

test:
  commands:
    - $R -e "library('rPref')"           # [not win]
    - "\"%R%\" -e \"library('rPref')\""  # [win]

about:
  home: https://www.p-roocks.de/rpref
  license: GPL-2.0-or-later
  summary: Routines to select and visualize the maxima for a given strict partial order. This especially includes the computation of the Pareto frontier, also known as (Top-k) Skyline operator (see Börzsönyi, et al.  (2001) <doi:10.1109/ICDE.2001.914855>), and some generalizations  known as database preferences (see Kießling
    (2002)  <doi:10.1016/B978-155860869-6/50035-4>).
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rPref
# Version: 1.3
# Date: 2019-02-15
# Title: Database Preferences and Skyline Computation
# Author: Patrick Roocks <mail@p-roocks.de>
# Maintainer: Patrick Roocks <mail@p-roocks.de>
# Description: Routines to select and visualize the maxima for a given strict partial order. This especially includes the computation of the Pareto frontier, also known as (Top-k) Skyline operator (see Borzsonyi, et al.  (2001) <doi:10.1109/ICDE.2001.914855>), and some generalizations  known as database preferences (see Kieling (2002)  <doi:10.1016/B978-155860869-6/50035-4>).
# URL: https://www.p-roocks.de/rpref
# Depends: R (>= 3.1.2)
# Imports: Rcpp (>= 1.0.0), RcppParallel (>= 4.3.6), dplyr (>= 0.8.0), igraph (>= 1.0.1), lazyeval (>= 0.2.1), methods, utils
# SystemRequirements: C++11, GNU make, Windows: cmd.exe and cscript.exe
# License: GPL (>= 2)
# LazyData: true
# LinkingTo: Rcpp, RcppParallel
# Suggests: testthat, graph, Rgraphviz (>= 2.16.0), knitr, ggplot2, rmarkdown
# Collate: 'rPref.r' 'RcppExports.R' 'pref-classes.r' 'base-pref.r' 'base-pref-macros.r' 'complex-pref.r' 'general-pref.r' 'pref-eval.r' 'show-pref.r' 'visualize.r' 'pred-succ.r'
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2019-02-15 23:35:04 UTC; patrick
# Repository: CRAN
# Date/Publication: 2019-02-16 10:00:03 UTC
