appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: IdFQx+zdf1KhkIEXpoS4sH6sGIHUTj2BC1M1ZVz7qN+upq12xQG8DAx+RMfJkglTkaKBdqNB2LHctOtnda4wqINBe0bZprVx7xhF7eUmMMcR5CEmSXHsFFYwOw3hVj8hRWm3I/ZYEINPRs6jVmAvfF++ek6yrq/FTApOPcy8WAd/HmeKkL5kbGwNoRVz72h652AFvy32yhbHWBFJQ85lA+VvUlU8OKeboZQqeCIGoUCNGHzUbBWjM/Kf/q7Fl5ldrqFuFd9kljpHbbCevVu34USFV8yPJGyT6KLLKqW+SqyLk8nvs4oRiuQHRp4a6UGPMkBN+RMqv5yzMbdkgi2n0ljS+Vjp1343deWmr83Q37e+QpdrhKTk0avyk6ZAD5uHrVzeuPgXTGOCA9TD+9vpZm6jKHdaiI9QXX3SESwLc2z3uUs8LAMlrpPe3BLN6z3Pu1/SR8gmyry+AYG0X7/loWaPmQsOy7UaYQ7cUXQGYsC25EK/5cJ9QOjC/qj7MdX+aFw+oGS+Ghz6Eodc+MujuEfQ6y2I57x2ZaKPLE8/cgvLg5tNKDzQfJ4Mv5BgZCq/If8ao6EEfp1oSMNJHulu1a2AafivjUiy3xJXN1iJqpsTBLLvOwY/350k5TEoKYkdrCu54NoxAjXkK0PFvbEiOQ6/mSt7eM2tla8QpR9xNUs=
conda_forge_output_validation: false
